import type { Metadata } from "next";
import { Inter } from "next/font/google";  // import Inter font
import "./globals.css";
import { Providers } from "@/components/sheard/session-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400", "500", "600", "700", "800", "900"
  ], 

});

export const metadata: Metadata = {
  title: "Table Fresh",
  description: "Generated by create next app",
   icons: {
    icon: "/asset/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
